name: Jason.Torrado
favicon: null
layout_spectrum: 0.50499
typography_spectrum: 0.3367211096920073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#210000'
    - '#ff2129'
    - '#ffff00'
    - '#ffffff'
    - '#ffae27'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
